# Aquisition Frequency of OptoForce Sensor Data
acquisition_rate: 1000 # in Hz

# Publish rate in Hz
publish_rate: 100

# OptoForce Sensors to be opened
devices:
  - name: "64 v0.9"       # Serial Number of the Device. IRE005 Blue Box
    calibration: [92.6,93.6,20.12,5054.3,5085.4,6912.5]  # IRE005 Calibration from Sensitivity Report
    speed: 1000           # Transmission frequency in Hz
    force_matrix:
      rows: 3
      cols: 3
      data: [ 0, 1, 0, -1, 0, 0, 0, 0, -1]
    torque_matrix:
      rows: 3
      cols: 3
      data: [ 0, 1, 0, 1, 0, 0, 0, 0, 1]

  - name: "95 v1.0"       # Serial Number of the Device. IRE004 Black Box
    calibration: [97.78,101.72,20.53,5210.6,5267.2,7659.7]  # IRE004 Calibration from Sensitivity Report
    speed: 1000           # Transmission Frequency in Hz
    force_matrix:
      rows: 3
      cols: 3
      data: [ 0, -1, 0, -1, 0, 0, 0, 0, 1]
    torque_matrix:
      rows: 3
      cols: 3
      data: [ 0, -1, 0, 1, 0, 0, 0, 0, 1]
